"""Contenido de los nodos reconstruidos bajo la arquitectura de 11 bloques.

Un módulo por nodo. Cada módulo expone `NODE_ID`, `CONCEPT_SLUG` y `CONTENT`
(el dict que viaja al frontend). `prealgebra.py` los recorre y los engancha:
agregar un nodo es crear su módulo y listarlo aquí — no se toca el renderer.
"""
from . import (
    b03_escalera,
    b04_naturales,
    b05_enteros,
    b06_racionales,
    b07_irracionales,
    b08_reales,
    b09_complejos,
    b10_clasificador_basico,
    b11_clasificador_riguroso,
    b12_detective,
    e01_suma,
    e02_resta,
    e03_multiplicacion,
    e04_division,
    e05_potenciacion,
    e06_radicacion,
    m01_conmutativa,
    m02_asociativa,
    m03_distributiva,
    m04_neutro,
    m05_inversos,
    c01_divisibilidad,
    c02_multiplos,
    c03_primos,
    c04_factorizacion,
    c05_mcd,
    c06_mcm,
    l01_variables,
    l02_constantes,
    l03_traduccion,
    l04_valor_numerico,
    o01_semejantes,
    o02_signos,
    o03_producto,
    o04_cociente,
    f01_simplificar,
    f02_suma,
    f03_producto,
    f04_division,
    r01_razones,
    r02_regla_de_tres,
    r03_porcentajes,
    r04_variacion,
    p01_cuadrado,
    p02_conjugados,
    p03_cubo,
    p04_termino_comun,
    g01_factor_comun,
    g02_cuadrados,
    g03_trinomio,
    g04_cubos,
    g05_expedicion,
)

# Orden de lectura del mapa, no de ejecución.
NODE_MODULES = [
    b03_escalera,
    b04_naturales,
    b05_enteros,
    b06_racionales,
    b07_irracionales,
    b08_reales,
    b09_complejos,
    b10_clasificador_basico,
    b11_clasificador_riguroso,
    b12_detective,
    # N2 · La ciudad de las operaciones: un edificio con nombre por nodo.
    e01_suma,
    e02_resta,
    e03_multiplicacion,
    e04_division,
    e05_potenciacion,
    e06_radicacion,
    # N3 · La fábrica de propiedades: una estación con nombre por nodo.
    m01_conmutativa,
    m02_asociativa,
    m03_distributiva,
    m04_neutro,
    m05_inversos,
    # N4 · El puerto de la polis: un destino con nombre por nodo.
    c01_divisibilidad,
    c02_multiplos,
    c03_primos,
    c04_factorizacion,
    c05_mcd,
    c06_mcm,
    # ALG-N1 · El Papiro de las Cuatro Casas: una casa de Kemet por nodo.
    l01_variables,
    l02_constantes,
    l03_traduccion,
    l04_valor_numerico,
    o01_semejantes,
    o02_signos,
    o03_producto,
    o04_cociente,
    f01_simplificar,
    f02_suma,
    f03_producto,
    f04_division,
    r01_razones,
    r02_regla_de_tres,
    r03_porcentajes,
    r04_variacion,
    p01_cuadrado,
    p02_conjugados,
    p03_cubo,
    p04_termino_comun,
    g01_factor_comun,
    g02_cuadrados,
    g03_trinomio,
    g04_cubos,
    g05_expedicion,
]

__all__ = ["NODE_MODULES"]
